name: swagger
description: Dart package to generate Swagger configuration files.
version: 1.0.0
homepage: https://github.com/mauriciotogneri/swagger-dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  http: ^0.12.1

dev_dependencies:
  build_runner: ^1.10.0
  test: ^1.14.5